version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: serene-flow-db
    environment:
      POSTGRES_DB: serene_flow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: serene-flow-backend
    depends_on:
      - postgres
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=serene_flow_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # Frontend Service (optional for development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: serene-flow-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: